### ISSUE TITLE
Mail icon missing

### ISSUE THREAD

**Issue by Skuriles** [Benik/BenikUI-TBC#12]
Hello, 
with latest version the mail icon is not shown. I've disabled all other addons but it is not there. 
With all disabled icons the post icon shows at the mini map.
I also checked different positions, offsets and resizing the minimap etc.
Nothing helped
Can I provide you any information what's going wrong?

**Comment by Benik** [comment]
In BenikUI -> Datatext options, is the setting you need :)

**Comment by Skuriles** [comment]
Ah thanks.. why is this disabled by default and can't be set globally for all chars as active?!
Just a question

Great mod btw.. thank you!

**Comment by Benik** [comment]
I have it disabled, cause a Mail Datatext is included in BenikUI, so this will tell when a new mail pops plus less clutter on the minimap. But it's good to have a choice toggling the setting :)

**Comment by Skuriles** [comment]
Soory, I'm new to ElvUi/BenikUi, how can I use this Mail Datatext to see when I get new mail?

**Comment by Benik** [comment]
For support, I strongly suggest to join BenikUI Discord -> https://discordapp.com/invite/8ZDDUem
The ticket system is for bugs only. Soz :)
