### ISSUE TITLE
[Wrath Bug Report] Multiple Lua errors after pre patch update

### ISSUE THREAD

**Issue by Dreadnaught503** [Benik/BenikUI-TBC#8]
When logging into wow my ui is telling me that i'm getting a lot of lua errors and to go into the interface for lua to see the errors but i don't see lua in the addons interface tab. One of the issues i am having is i can't put talent points into different perks in the talent tree. I'm hoping this gets fixed soon because my game is basically unplayable and i cant spec on any of my characters.

**Comment by Benik** [comment]
Please install v1.14
